### PR TITLE
(Fix) Update DApp loading code considering upcoming Breaking Change in MetaMask

### LINKED ISSUE #200: (Fix) Update DApp loading code considering upcoming Breaking Change in MetaMask
**Problem:** On `November 2nd, 2018` MetaMask and other DApp browsers will stop exposing user accounts by default. Instead, dapps must request access using a new provider method: `provider.enable()`. Detailed info is available here: https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

**Solution:** Fix the code which loads DApp according to instructions from `What this means for developers` section of the article mentioned above.

### PR DESCRIPTION
**Pull request by unjapones**
Closes #200 .

Modify the "MetaMask not found" error page to display a generic error text stating _"Wallet not found" + "access to Ethereum account not granted"_; i.e something in-between what we had previously and what was done for [PoBA in this PR](https://github.com/poanetwork/poa-poba/pull/69).

popa-eip1102

### CODE REVIEW

**Comment by phahulin** [comment]
@unjapones Although changes seem fine, it worries me that CI fails second time with `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`
Could you look into it?

**Comment by unjapones** [comment]
@phahulin yup! I'm on it :+1: 
Will leave the `in progress` label on this PR until I find what's happening. Will ping you when I have news.

**Comment by unjapones** [comment]
Not sure what's going on with POAS's builds queue, but the last commit I added seems to fix the [build, at least on my fork](https://travis-ci.org/unjapones/poa-popa/builds/442353878).

**Comment by unjapones** [comment]
@phahulin Travis build is green again :sunglasses:

**Review by phahulin — APPROVED** [review]
Nice

**Pull request merged**
