### PR TITLE
(Feature) Show list of registeded addresses

### PR DESCRIPTION
**Pull request by garatortiz**
Depends on #100.

- Add a list of addresses registered with the current account
- Add a remove button to allow the user to remove a registered address
- Show which addresses are already confirmed

### CODE REVIEW

**Comment by fvictorio** [comment]
@Janther I added an `unregisterAddress` method to the PoPA contract for the feature of removing registered addresses. Please take a look at it and tell me if you think that approach will work.

**Comment by matiasgaratortiz** [comment]
image

**Comment by garatortiz** [comment]
image

**Comment by fvictorio** [comment]
This is in a stable point right now, I think we can merge it and do the pending things (improving the styles and whatever issue we find later) in separate PRs.

**Review by fvictorio — APPROVED** [review]

**Comment by phahulin** [comment]
After #95 `popa.userAddressesCount` should be changed to `popa.userSubmittedAddressesCount`

**Comment by fvictorio** [comment]
> After #95 popa.userAddressesCount should be changed to popa.userSubmittedAddressesCount

Fixed, thanks.

**Pull request merged**
