### PR TITLE
Add postcards templates

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by igorbarinov — APPROVED** [review]

**Review by phahulin — CHANGES_REQUESTED** [review]
Please replace image here https://github.com/oraclesorg/oracles-dapps-proof-of-physical-address/pull/2/files#diff-a36b9c4f366c514fdb2d1d56c2017fbeR19
with its direct link (this one requires authentication).

**Comment by igorbarinov** [comment]
@phahulin we don't need this merge on master

I set up deployment of postcards from postcards-templates branch to Netlify and they are available at 
https://upholsterer-joe-75405.netlify.com/postcard1.html
https://upholsterer-joe-75405.netlify.com/postcard2.html

please use them for lob.com integration

**Comment by ghost** [comment]
@igorbarinov i suppose, for service we need absolute url's path, like this: ```https://upholsterer-joe-75405.netlify.com/images/postcard1.png```

**Comment by ghost** [comment]
in this case i was waiting for your deployment, i didn't know domain's name :)

**Comment by igorbarinov** [comment]
@phahulin do we need absolute path to images?

**Comment by phahulin** [comment]
@igorbarinov yes, because postcard is assembled from template on Lob's side. Also, these html files would need to be changed a little to become a valid template - confirmation code and confirmation page url must be replaced with corresponding placeholders, e.g. `{{confirmation_page_url}}`.

So actually it would be best to keep these files in master branch to be passed to Lob when creating new postcard.
There is an alternative way - we could create and store templates in Lob itself. Images would still need to be specified via an absolute path though.

I think it's easier to keep everything in one place - on our side, so we should use the first option here.

**Comment by igorbarinov** [comment]
we have postcards in a separate branch for deployment to Netlify, which host png and jpg files for free from the deployed branch.

Can we have jpg here and merge HTML to master branch?

https://upholsterer-joe-75405.netlify.com/images/postcard1.png
https://upholsterer-joe-75405.netlify.com/images/postcard2.jpg
for images

**Comment by phahulin** [comment]
@igorbarinov ok, added to dev branch for now in https://github.com/oraclesorg/oracles-dapps-proof-of-physical-address/commit/e4cbdfc888d7cdc5d7cec1dd0b5a24a8d325258f and https://github.com/oraclesorg/oracles-dapps-proof-of-physical-address/commit/4e8081c766a51e24c730f219ad5c4517af94d043

**Pull request closed without merging**
