### PR TITLE
(Improvement) Show the list of addresses in My Addresses as a grid

### PR DESCRIPTION
**Pull request by garatortiz**
Before submitting a pull request, please provide the following information:

- **What is it?** (leave one option)
    * `(Improvement)` of existing functionality

- **What was the root cause of the problem originally / what feature was missing?**
Show the registered addresses as a grid instead of a list.

- **How does this pull request solve it (in broad terms)?**

- **Does it close any open issues?**
No

- **Quick checklist**
    - [x] `npm run lint` shows no errors
    - [x] docs were updated where necessary OR they don't need to be updated
    - [x] tests were updated where necessary OR they don't need to be updated

- **Additional information**

### CODE REVIEW

**Review by phahulin — APPROVED** [review]

**Comment by garatortiz** [comment]
image

**Comment by garatortiz** [comment]
image

**Comment by phahulin** [comment]
@matiasgaratortiz maybe also add creation date and confirmation date?

**Comment by garatortiz** [comment]
@phahulin we have not this info in the contract...

**Comment by phahulin** [comment]
Is this ready for review? (still has "In progress" label)

**Comment by garatortiz** [comment]
@phahulin yes, it's ready

**Pull request merged**
