### PR TITLE
Apply new graphic design

### LINKED ISSUE #141: (Improvement) Apply new graphic design

### PR DESCRIPTION
**Pull request by garatortiz**
Closes #141

**Note:** Frontend tests are failing.

### CODE REVIEW

**Comment by fvictorio** [comment]
Things I noticed:

- The confirmed addresses are not differentiated from the unconfirmed.
- The home logo doesn't work (clicking it doesn't take you to the home page).
- I think we should have a back button in the addresses page too.

**Comment by fernandomg** [comment]
Small details I've found so far:
- If I press enter on the confirmation code input, page reloads with the query param `?confirmationCodePlain=` added to the URL. If I click on the arrow button, everything works fine.
- button in confirm input is not aligned to the input itself
- back arrow icon not vertically centered
- in portrait mobile layout _loading_ icon is not horizontally centered
- medium should be: `https://medium.com/poa-network`
- missing question marks in form labels
- for display with a width between `320px` and `1300px`, _Proof of Physical Address_ legend in logo looks like a serif-like font

**Comment by garatortiz** [comment]
To make the question marks work, we need add this code. How can I add this code in the React view?

```
 $(".info").hover(
		  function () {
		    $(this).find('.hidden-info').fadeOut();
		    $(this).find('.hidden-info').fadeIn();

		  },
		  function () {
		    $(this).find('.hidden-info').fadeIn();
		    $(this).find('.hidden-info').fadeOut();
		  }
		)
```

**Comment by garatortiz** [comment]
@fvictorio @fernandomg it's ready to review

**Review by fvictorio — APPROVED** [review]

**Review by fernandomg — APPROVED** [review]

**Comment by phahulin** [comment]
Few more things I noticed. Let me know if those are out of scope of this PR, and will go to a different PRs:
1. page icon (on chrome tab) is from the previous version (eye in triangle)
2. "How it works" button doesn't work (if I click on it - nothing happens)
3. when opening "My addresses" page, the image on the left side of the page scales up
4. postcards are still in the previous version of design
5. there is margin on top of each page. On some pages (`/register`, `/confirm`) this leads to emergence of vertical scroll bar, maybe remove them if possible
selection-2018-05-29-01 38 10-001
6. on "my addresses" page footer "2018 POA..." goes up to the middle of the page (depending on the amount of addresses in the list)
7. "register new address" page leads to /register route, which is not declared in `web-dapp/app.js`
https://github.com/poanetwork/poa-popa/blob/master/web-dapp/app.js#L13-L15
https://github.com/poanetwork/poa-popa/blob/master/web-dapp/app.js#L22-L23
if you copy url and paste it in incognito mode you get "Cannot GET /register" 404 error

**Comment by garatortiz** [comment]
@phahulin done!

**Comment by phahulin** [comment]
Postcard templates are mixed up - back and front covers should be swaped

**Review by phahulin — APPROVED** [review]

**Pull request merged**
